[metadata]
name = quadlogit
version = attr: quadlogit.__version__
author = Zizhong Yan and Shiran Hu
author_email = helloyzz@gmail.com
description = Quadruple logit regression for network formation models
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/zizhongyan/quadlogit
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

project_urls =
    Source = https://github.com/zizhongyan/quadlogit
    Documentation = https://quadlogit.readthedocs.io/
    Issues = https://github.com/zizhongyan/quadlogit/issues

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
zip_safe = False
install_requires =
    numpy
    scipy
    pandas
    torch

[options.packages.find]
include =
    quadlogit
    quadlogit.*
exclude =
    tests
    tests.*